### ISSUE TITLE
no plots in OASYS 1,3 with matplot 3.6.0 

### ISSUE THREAD

**Issue by srio** [oasys-kit/OASYS1#11]
In ubuntu, oasys1.3 gives errors in all plots using matplotlib 3.6.0

There are no problems with matplotlib 3.5.3

This is not affecting oasys 1.2: apparently python 3.7 does not update to matplotlib 3.6.0

The error comes from plots with silx. I will check that tomorrow and, if necessary, send an issue to silx. 

A command line matplotlib plot does work. 

For the moment I think is important to limit in oasys1  matplotlib<=3.5.3 (or <3.6.0)

This is the error using wofry/generic wavefront 1D:

```
TypeError                                     Traceback (most recent call last):
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/orangecontrib/wofry/widgets/wavefront_propagation/ow_generic_wavefront_1D.py", line 382, in generate
    self.plot_results()
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/orangecontrib/wofry/widgets/gui/ow_wofry_widget.py", line 108, in plot_results
    self.do_plot_results(progressBarValue)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/orangecontrib/wofry/widgets/wavefront_propagation/ow_generic_wavefront_1D.py", line 406, in do_plot_results
    self.plot_data1D(x=1e6*self.wavefront1D.get_abscissas(),
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/orangecontrib/wofry/widgets/gui/ow_wofry_widget.py", line 125, in plot_data1D
    self.plot_canvas[plot_canvas_index] = oasysgui.plotWindow(parent=None,
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/oasys/widgets/gui.py", line 311, in plotWindow
    plot_window = PlotWindow(parent=parent, backend=backend,
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/silx/gui/plot/PlotWindow.py", line 114, in __init__
    super(PlotWindow, self).__init__(parent=parent, backend=backend)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/silx/gui/plot/PlotWidget.py", line 392, in __init__
    self._backend = self.__getBackendClass(backend)(self, self)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/oasys/widgets/gui.py", line 289, in __init__
    super().__init__(plot, parent)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/silx/gui/plot/backends/BackendMatplotlib.py", line 1334, in __init__
    FigureCanvasQTAgg.__init__(self, self.fig)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 209, in __init__
    super().__init__(figure=figure)
  File "/home/esrf/srio/miniconda3-py38/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1656, in __init__
    super().__init__()  # Typically the GUI widget init (if any).
TypeError: __init__() missing 1 required positional argument: 'plot'



```

**Comment by lucarebuffi** [comment]
I know the issue, and I thought I did limit the version!....oooops

**Comment by srio** [comment]
You limited silx==0.15.0 but not matplotlib. 

I informed silx people: https://github.com/silx-kit/silx/issues/3684 

Thanks!!!!!!

**Comment by lucarebuffi** [comment]
fixed

**Comment by srio** [comment]
did you change setup.py in oasys1? 
I still see ```matplotlib>=3.3.2```
Cheers, M

**Comment by lucarebuffi** [comment]
now I pushed the modifications, sorry
