### ISSUE TITLE
OASYS not opening

### ISSUE THREAD

**Issue by Johirul5** [oasys-kit/OASYS1#14]
Hi,
I was trying open oasys in windows today (python version 3.8.5) but its not working anymore. It was working fine just a few days ago. 

This is the error message I get after I try to start it with "python -m oasys.canvas":

(base) C:\Users\johirul.islam>python -m oasys.canvas
Traceback (most recent call last):
  File "C:\Users\johirul.islam\Miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\johirul.islam\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\canvas\__main__.py", line 490, in <module>
    sys.exit(main())
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\canvas\__main__.py", line 452, in main
    raise e
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\canvas\__main__.py", line 279, in main
    canvas_window = OASYSMainWindow(parent=None, no_update=no_update)
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\canvas\mainwindow.py", line 500, in __init__
    if not no_update: self.__set_pypi_internal_libraries(load_pypi_internal_libraries())
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\canvas\mainwindow.py", line 576, in __set_pypi_internal_libraries
    if internal_libraries.is_updatable(item):     self.__internal_library_to_update.append(item)
  File "C:\Users\johirul.islam\Miniconda3\lib\site-packages\oasys\application\internal_libraries.py", line 95, in is_updatable
    if MAX_VERSION[dist.project_name] is None: return True
KeyError: 'SciPy'

**Comment by lucarebuffi** [comment]
Christmas gift by Python Package Index. 

open Miniconda Prompt:

(Start Menu->Anaconda3->Anaconda Prompt (miniconda3))

then type:

python -m pip install oasys1 --upgrade

**Comment by Johirul5** [comment]
Awesome, thank you its working now. 👍
